EDAD = int(input("DIGITE SU EDAD EN AÑOS SOLAMETE: "))
AÑO= int(input("DIGITE EL AÑO EN CURSO: "))
PREDICCION=int(input("DIGITE EL AÑO EN EL CUAL QUIERE SABER SU EDAD: "))
FUTURO=PREDICCION-AÑO
EDAD2=EDAD+FUTURO
print('su edad parA el año 2070 es:',EDAD2)